project_id = "kfskqhgziuzowfoemqbg"

[functions.send-email]
verify_jwt = false

[functions.file-proxy]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.emit-fel]
verify_jwt = false

[functions.cybersource-auth-test]
verify_jwt = false

[functions.upload-receipt]
verify_jwt = false

[functions.cybersource-sign]
verify_jwt = false

[functions.cybersource-return]
verify_jwt = false

[functions.notify-donation]
verify_jwt = false
