project_id = "kfskqhgziuzowfoemqbg"

[functions.send-email]
verify_jwt = false

[functions.file-proxy]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.emit-fel]
verify_jwt = false

[functions.cybersource-auth-test]
verify_jwt = false
